-- Tabela equipment_catalog com todas as 118 colunas do CSV
-- Substitui a versão anterior com apenas 22 colunas

drop table if exists public.equipment_catalog;

create table public.equipment_catalog (
  modelo                             text primary key,
  modelo_unico                       text,
  status_compressor                  text,
  modelo_catalogo_original           text,
  modelo_base_referencia             text,
  fabricante                         text,
  fabricante_origem                  text,
  compressor_modelo                  text,
  compressor_codigo                  text,
  tipo_compressor                    text,
  configuracao_eletrica              text,
  tensao_eletrica_descricao          text,
  tensao_v                           numeric,
  numero_fases                       integer,
  frequencia_hz                      integer,
  linha                              text,
  designacao_hp                      text,
  gabinete                           text,
  tipo_gabinete                      text,
  refrigerante                       text,
  cap_reaquecimento_kcalh            numeric,
  cap_compressor_kcalh               numeric,
  calor_rejeitado_kcalh              numeric,
  pot_total_circuito_kw              numeric,
  corrente_circuito_a                numeric,
  corrente_partida_circuito_a        numeric,
  cop_global                         numeric,
  gwp                                numeric,
  odp                                numeric,
  tipo_degelo                        text,
  cond_rows                          integer,
  cond_tubes_per_row                 integer,
  cond_circuits                      integer,
  cond_fin_spacing_mm                text,
  cond_length_mm                     text,
  cond_tubo_in                       text,
  cond_tubo_mm                       numeric,
  cond_tubo_esp_mm                   numeric,
  cond_geometria                     text,
  cond_volume_l                      numeric,
  cond_ventilador                    text,
  cond_vazao_m3h                     numeric,
  evap_rows                          integer,
  evap_tubes_per_row                 integer,
  evap_circuits                      integer,
  evap_fin_spacing_mm                text,
  evap_length_mm                     text,
  reheat_rows                        integer,
  evap_geometria                     text,
  reheat_tubes_per_row               integer,
  reheat_circuits                    integer,
  reheat_fin_spacing_mm              text,
  reheat_length_mm                   text,
  evap_tubo_in                       text,
  evap_tubo_mm                       numeric,
  evap_tubo_esp_mm                   numeric,
  reheat_geometria                   text,
  evap_volume_l                      numeric,
  evap_area_m2                       numeric,
  reheat_quantidade                  integer,
  evap_ventilador                    text,
  evap_vazao_m3h                     numeric,
  temp_camara_c                      numeric,
  umidade_camara_pct                 numeric,
  temp_evaporacao_c                  numeric,
  temp_condensacao_c                 numeric,
  temp_ambiente_c                    numeric,
  umidade_externa_pct                numeric,
  vazao_massa_kgh                    numeric,
  vazao_massa_kgs                    numeric,
  delta_entalpia_kjkg                numeric,
  superaquecimento_total_k           numeric,
  superaquecimento_util_k            numeric,
  subresfriamento_k                  numeric,
  subresfriamento_adicional_k        numeric,
  altitude_m                         numeric,
  linha_descarga                     text,
  vel_descarga_ms                    text,
  linha_liquido                      text,
  vel_liquido_ms                     text,
  linha_succao                       text,
  vel_succao_ms                      text,
  carga_fluido_kg                    text,
  agua_produzida_lh                  text,
  diametro_dreno                     text,
  quantidade_drenos                  integer,
  pot_compressor_kw                  numeric,
  pot_ventilador_kw                  numeric,
  pot_total_kw                       numeric,
  cop                                numeric,
  cop_carnot                         numeric,
  corrente_compressor_a              numeric,
  corrente_ventiladores_a            numeric,
  corrente_total_a                   numeric,
  corrente_partida_a                 numeric,
  sec_modelo_condensador             text,
  sec_ventilador_condensador         text,
  sec_vazao_cond_m3h                 numeric,
  sec_modelo_trocador                text,
  sec_cap_req_kcalh                  numeric,
  sec_cap_comp_kcalh                 numeric,
  sec_calor_rejeitado_kcalh          numeric,
  sec_temp_entrada_c                 numeric,
  sec_temp_saida_c                   numeric,
  sec_temp_evap_c                    numeric,
  sec_temp_cond_c                    numeric,
  sec_superaq_total_k                numeric,
  sec_superaq_util_k                 numeric,
  sec_subresfr_k                     numeric,
  sec_pot_comp_kw                    numeric,
  sec_pot_vent_kw                    numeric,
  sec_pot_total_kw                   numeric,
  sec_cop                            numeric,
  sec_cop_carnot                     numeric,
  sec_corrente_comp_a                numeric,
  sec_corrente_vent_a                numeric,
  sec_corrente_total_a               numeric,
  sec_corrente_partida_a             numeric,
  validation_status         text not null default 'pending'
                              check (validation_status in ('pending','approved','warning','rejected')),
  data                      jsonb not null default '{}',
  validated_at              timestamptz,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

create index if not exists equip_cat_linha_idx    on public.equipment_catalog (linha);
create index if not exists equip_cat_refrig_idx   on public.equipment_catalog (refrigerante);
create index if not exists equip_cat_valid_idx    on public.equipment_catalog (validation_status);
create index if not exists equip_cat_data_gin     on public.equipment_catalog using gin (data);

alter table public.equipment_catalog enable row level security;

drop policy if exists "equipment_catalog read" on public.equipment_catalog;
create policy "equipment_catalog read" on public.equipment_catalog
  for select to authenticated using (true);

drop policy if exists "equipment_catalog admin write" on public.equipment_catalog;
create policy "equipment_catalog admin write" on public.equipment_catalog
  for all to authenticated
  using (exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin'))
  with check (exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin'));