-- equipment_catalog: 118 colunas com nomes exatos do CSV (snake_case)
-- Gerado automaticamente de catalogo_480_modelos_codigo_completo_corrigido_rev01.csv

drop table if exists public.equipment_catalog cascade;

create table public.equipment_catalog (
  modelo                                                   text,
  modelo_unico                                             text,
  status_compressor                                        text,
  modelo_catalogo_original                                 text,
  modelo_base_referencia                                   text,
  fabricante                                               text,
  fabricante_origem                                        text,
  compressor                                               text,
  compressor_codigo                                        text,
  tipo_compressor                                          text,
  configuracao_eletrica                                    text,
  tensao_eletrica_v                                        text,
  tensao_v                                                 numeric,
  numero_fases                                             integer,
  frequencia_hz                                            integer,
  linha                                                    text,
  designacao_comercial_em_hp                               text,
  gabinete                                                 text,
  tipo_de_gabinete                                         text,
  refrigerante                                             text,
  capacidade_frigorifica_kcal_h_capacidade_do_reaquecimento numeric,
  capacidade_frigorifica_kcal_h_capacidade_do_compressor   numeric,
  calor_rejeitado_kcal_h_capacidade_do_condensador         numeric,
  potencia_eletrica_requerida_total_circuito_completo_kw   numeric,
  corrente_eletrica_estimada_circuito_completo_a           numeric,
  corrente_eletrica_de_partida_circuito_completo_a         numeric,
  cop_global_kw_kw                                         numeric,
  gwp_ar6                                                  numeric,
  odp_ar6                                                  numeric,
  tipo_de_degelo                                           text,
  condensador_rows                                         integer,
  condensador_tubes_per_row                                integer,
  condensador_circuits                                     integer,
  condensador_fin_spacing_mm                               text,
  condensador_length_mm                                    text,
  o_tubo_cond_in                                           text,
  o_tubo_cond_mm                                           numeric,
  esp_tubo_cond_mm                                         numeric,
  geometria_condensador                                    text,
  volume_interno_condensador_dm_l                          numeric,
  ventilador_condensador                                   text,
  vazao_ventilador_condensador_m_h                         numeric,
  eaporadorrows                                            integer,
  eaporadortubes_per_row                                   integer,
  eaporadorcircuits                                        integer,
  eaporador_fin_spacing_mm                                 text,
  eaporador_length_mm                                      text,
  eaporadorrows_1                                          integer,
  geometria_evaporador                                     text,
  reaquecimento_tubes_per_row                              integer,
  reaquecimento_circuits                                   integer,
  reaquecimento_fin_spacing_mm                             text,
  reaquecimento_length_mm                                  text,
  o_tubo_evap_in                                           text,
  o_tubo_evap_mm                                           numeric,
  esp_tubo_evap_mm                                         numeric,
  geometria_reaquecimento                                  text,
  volume_interno_eaporador_dm_l                            numeric,
  area_da_superficie_de_troca_eaporador_m                  numeric,
  quantidade_de_reaquecimentoes                            integer,
  ventilador_reaquecimento                                 text,
  vazao_ventilador_eaporador_m_h                           numeric,
  temperatura_da_camara_c                                  numeric,
  umidade_da_camara                                        numeric,
  temperatura_de_evaporacao_c                              numeric,
  temperatura_de_condensacao_c                             numeric,
  temperatura_externa_c                                    numeric,
  umidade_externa                                          numeric,
  vazao_em_massa_kg_h                                      numeric,
  vazao_em_massa_kg_s                                      numeric,
  diferenca_de_entalpia_kj_kg                              numeric,
  superaquecimento_total_k                                 numeric,
  superaquecimento_util_k                                  numeric,
  subresfriamento_k                                        numeric,
  subresfriamento_adicional_k                              numeric,
  altitude_m                                               numeric,
  linha_de_descarga                                        text,
  velocidade_linha_de_descarga_m_s_ate_15m                 text,
  linha_de_liquido                                         text,
  velocidade_linha_de_liquido_m_s_ate_15m                  text,
  linha_de_succao                                          text,
  velocidade_linha_de_succao_m_s_ate_15m                   text,
  carga_de_fluido_kg                                       text,
  quantidade_de_agua_produzida_l_h                         text,
  diametro_dreno                                           text,
  quantidade_de_drenos                                     integer,
  potencia_eletrica_requerida_compressor_kw                numeric,
  potencia_eletrica_requerida_ventilador_kw                numeric,
  potencia_eletrica_requerida_total_kw                     numeric,
  cop_kw_kw                                                numeric,
  cop_carnot_k_k                                           numeric,
  corrente_eletrica_compressor_a                           numeric,
  corrente_eletrica_ventiladores_a                         numeric,
  corrente_eletrica_estimada_a                             numeric,
  corrente_eletrica_de_partida_a                           numeric,
  modelo_condensador_secundario                            text,
  ventilador_condensador_secundario                        text,
  vazao_ventilador_condensador_secundario_m_h              numeric,
  modelo_tocador_de_calor                                  text,
  capacidade_frigorifica_requisitada_kcal_h                numeric,
  capacidade_frigorifica_do_compressor_kcal_h              numeric,
  calor_rejeitado_secundario_kcal_h                        numeric,
  temperatura_de_entrada_c                                 numeric,
  temperatura_de_saida_c                                   numeric,
  temperatura_de_evaporacao_secundario_c                   numeric,
  temperatura_de_condensacao_secundario_c                  numeric,
  superaquecimento_total_secundario_k                      numeric,
  superaquecimento_util_secundario_k                       numeric,
  subresfriamento_secundario_k                             numeric,
  potencia_eletrica_requerida_compressor_secundario_kw     numeric,
  potencia_eletrica_requerida_ventilador_secundario_kw     numeric,
  potencia_eletrica_requerida_total_secundario_kw          numeric,
  cop_secundario_kw_kw                                     numeric,
  cop_carnot_secundario_k_k                                numeric,
  corrente_eletrica_compressor_secundario_a                numeric,
  corrente_eletrica_ventiladores_secundario_a              numeric,
  corrente_eletrica_estimada_secundario_a                  numeric,
  corrente_eletrica_de_partida_secundario_a                numeric,
  validation_status              text not null default 'pending'
                                   check (validation_status in ('pending','approved','warning','rejected')),
  data                           jsonb not null default '{}',
  validated_at                   timestamptz,
  created_at                     timestamptz not null default now(),
  updated_at                     timestamptz not null default now(),
  constraint equipment_catalog_pkey primary key (modelo)
);

create index if not exists equip_cat_linha_idx    on public.equipment_catalog (linha);
create index if not exists equip_cat_refrig_idx   on public.equipment_catalog (refrigerante);
create index if not exists equip_cat_valid_idx    on public.equipment_catalog (validation_status);
create index if not exists equip_cat_data_gin     on public.equipment_catalog using gin (data);

alter table public.equipment_catalog enable row level security;

drop policy if exists "equipment_catalog read" on public.equipment_catalog;
create policy "equipment_catalog read" on public.equipment_catalog
  for select to authenticated using (true);

drop policy if exists "equipment_catalog admin write" on public.equipment_catalog;
create policy "equipment_catalog admin write" on public.equipment_catalog
  for all to authenticated
  using (exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin'))
  with check (exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin'));
